apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "main"

jobs:
   register_build_artifact:
      name: Default commit
      uses: cloudbees-io/register-build-artifact@v2
      with:
        name: "myApp"
        url: "docker.io/myapp/myimg:1.0.0"
        version: "1.0.0",
        type: "docker"

   register_build_artifact_user:
      name: User commit
      uses: cloudbees-io/register-build-artifact@v2
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: "myApp"
          url: "docker.io/myapp/myimg:1.0.0"
          version: "1.0.0",
          type: "docker"
          repository-url: "https://github.com/karthiknaveene/ideal-disco",
          commit: "01539735a702575dd28ee5c172fa771e5708d2d0",
          ref: "refs/heads/main",
          
