apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v1.0.6
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        id: checkout
      - name: User commit
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: myApp
          url: docker.io/myapp/myimg:1.0.0
          version: 1.0.0
          repository-url: https://github.com/karthiknaveene/ideal-disco
          commit: 01539735a702575dd28ee5c172fa771e5708d2d0
          ref: refs/heads/main
          labels: User Defined
      - name: Default commit
        uses: cloudbees-io/register-build-artifact@v2
        id: register-1
        with:
          name: myApp
          url: docker.io/myapp/myimg:1.0.0
          version: 1.0.0
          labels: Default
