apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        id: checkout
      - name: Register an artifact with the CloudBees Unify
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "myApp"
          url: "docker.io/myapp/myimg:1.0.0"
          version: "1.0.0"
          repository-url: "https://github.com/karthiknaveene/ideal-disco"
          commit: "01539735a702575dd28ee5c172fa771e5708d2d0"
          ref: "refs/heads/main"
      - name: Print output parameter artifact ID
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "artifact ID for myApp:${{ cloudbees.version }} is: ${{ steps.register.outputs.artifact-id }}"
          
          
